#!/bin/bash

killall hyprpaper 2>/dev/null

conf_file="$HOME/.config/hypr/config/monitors_variables.conf"
out_file="$HOME/.config/hypr/hyprpaper.conf"


declare -A monitors
declare -A wallpapers
while IFS= read -r line; do
    if [[ "$line" =~ ^\$monitor([0-9]+)[[:space:]]*=[[:space:]]*(.+)$ ]]; then
        idx="${BASH_REMATCH[1]}"
        monitors[$idx]="${BASH_REMATCH[2]}"
    fi
    if [[ "$line" =~ ^\$wallpaper([0-9]+)[[:space:]]*=[[:space:]]*(.+)$ ]]; then
        idx="${BASH_REMATCH[1]}"
        wallpapers[$idx]="${BASH_REMATCH[2]}"
    fi
done < "$conf_file"


{
    echo "# Generated by generate-hyprpaper.sh"
    echo "# Modify variables in monitors_variables.conf"
    echo ""
    
    for i in "${!monitors[@]}"; do
        if [[ -n "${wallpapers[$i]}" ]]; then
            echo "wallpaper {"
            echo "    monitor = ${monitors[$i]}"
            echo "    path = ${wallpapers[$i]}"
            echo "    fit_mode = cover"
            echo "}"
        fi
    done

    
    if [[ -n "${wallpapers[1]}" ]]; then
        echo "wallpaper {"
            echo "    monitor ="
            echo "    path = ${wallpapers[1]}"
            echo "    fit_mode = cover"
            echo "}"
    fi

    echo "splash = false"
} > "$out_file"

hyprpaper &
