#exec = gsettings set org.gnome.desktop.interface color-scheme prefer-dark
#exec = gsettings set org.gnome.desktop.interface gtk-theme catppuccin-frappe-green-standard+default

exec-once = swww-daemon # Wallpaper daemon
exec-once = waybar # Status bar
exec-once = hypridle # Idle and lockscreen daemon
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent # Polkit agent
exec-once = gammastep -P # Blue light filter
exec-once = udiskie --tray # Portable devices auto-mount
