$terminal = kitty
$fileManager = $terminal yazi
$menu = rofi -show drun 
$editor = $terminal nvim
$powerMenu = rofi -show power-menu -modi "power-menu:rofi-power-menu --choices=shutdown/reboot/logout/lockscreen/suspend"
$emojiPicker = ~/.config/hypr/scripts/ep.sh 
