# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Gaming workspace (10)
windowrulev2 = fullscreen,class:^steam_app\d+$
windowrulev2 = monitor 1,class:^steam_app_\d+$
windowrule = opacity 1.0 override 1.0 override, workspace:10
windowrule = noblur, workspace:10
## Games
windowrulev2 = workspace 10,class:^steam_app_\d+$
windowrulev2 = workspace 10, class:org.prismlauncher.PrismLauncher
windowrulev2 = workspace 10, class:steam

# By apps
windowrulev2 = workspace 9, class:firefox

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Floating rules
windowrule = float,class:org.telegram.desktop
